//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JhDeStip.Laguna.Client.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JhDeStip.Laguna.Client.Resources.UIStrings", typeof(UIStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef een zoekterm in.
        /// </summary>
        internal static string EnterSearchTerm {
            get {
                return ResourceManager.GetString("EnterSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foutje :(.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden….
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen resultaten.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er staan geen nummers in de wachtrij.
        /// </summary>
        internal static string NothingInQueue {
            get {
                return ResourceManager.GetString("NothingInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er wordt niks afgespeeld.
        /// </summary>
        internal static string NothingPlaying {
            get {
                return ResourceManager.GetString("NothingPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer toevoegen?.
        /// </summary>
        internal static string QAddTrack {
            get {
                return ResourceManager.GetString("QAddTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wil je {0} toevoegen aan de wachtrij?.
        /// </summary>
        internal static string QDoYouWantToAddTrackToQueue {
            get {
                return ResourceManager.GetString("QDoYouWantToAddTrackToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken….
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dienst is momenteel niet beschikbaar.
        /// </summary>
        internal static string ServiceCurrentlyNotAvailable {
            get {
                return ResourceManager.GetString("ServiceCurrentlyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dienst niet beschikbaar.
        /// </summary>
        internal static string ServiceNotAvailable {
            get {
                return ResourceManager.GetString("ServiceNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgegaan.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgegaan waardoor we het nummer niet konden toevoegen aan de wachtrij… Niet getreurd, je krijgt een troostkusje van de tapper!.
        /// </summary>
        internal static string SomethingWentWrongCouldNotAddTrackToQueueKissFromBartender {
            get {
                return ResourceManager.GetString("SomethingWentWrongCouldNotAddTrackToQueueKissFromBartender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer toevoegen.
        /// </summary>
        internal static string TrackAdded {
            get {
                return ResourceManager.GetString("TrackAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummer al in wachtrij.
        /// </summary>
        internal static string TrackAlreadyInQueue {
            get {
                return ResourceManager.GetString("TrackAlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit nummer staat al in de wachtrij. Even geduld, het komt eraan! :).
        /// </summary>
        internal static string TrackAlreadyInQueuePatience {
            get {
                return ResourceManager.GetString("TrackAlreadyInQueuePatience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je nummer staat klaar om afgespeeld te worden!.
        /// </summary>
        internal static string YourTrackIsQueuedToPlay {
            get {
                return ResourceManager.GetString("YourTrackIsQueuedToPlay", resourceCulture);
            }
        }
    }
}
