//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JhDeStip.Laguna.Player.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JhDeStip.Laguna.Player.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie is beschikbaar.
        /// </summary>
        public static string ApplicationIsAvailable {
            get {
                return ResourceManager.GetString("ApplicationIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie is niet beschikbaar.
        /// </summary>
        public static string ApplicationIsNotAvailable {
            get {
                return ResourceManager.GetString("ApplicationIsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan beschikbaarheid niet ophalen.
        /// </summary>
        public static string CannotRetrieveServiceAvailability {
            get {
                return ResourceManager.GetString("CannotRetrieveServiceAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met opruimen van cache en tijdelijke bestanden….
        /// </summary>
        public static string CleaningUpCacheAndTempFiles {
            get {
                return ResourceManager.GetString("CleaningUpCacheAndTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan applicatie niet aanzetten..
        /// </summary>
        public static string DialogText_CannotMakeServiceAvailable {
            get {
                return ResourceManager.GetString("DialogText_CannotMakeServiceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan applicatie niet uitzetten..
        /// </summary>
        public static string DialogText_CannotMakeServiceUnavailable {
            get {
                return ResourceManager.GetString("DialogText_CannotMakeServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan backupafspeellijst niet vernieuwen op server..
        /// </summary>
        public static string DialogText_CannotRefreshFallbackPlaylistOnServer {
            get {
                return ResourceManager.GetString("DialogText_CannotRefreshFallbackPlaylistOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan nummer niet verwijderen..
        /// </summary>
        public static string DialogText_CannotRemoveTrack {
            get {
                return ResourceManager.GetString("DialogText_CannotRemoveTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn missende of ongeldige waarden in het configuratiebestand..
        /// </summary>
        public static string DialogText_MissingOrInvalidValuesInConfiguration {
            get {
                return ResourceManager.GetString("DialogText_MissingOrInvalidValuesInConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mislukt.
        /// </summary>
        public static string DialogTitle_Failed {
            get {
                return ResourceManager.GetString("DialogTitle_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig configuratiebestand.
        /// </summary>
        public static string DialogTitle_InvalidConfiguration {
            get {
                return ResourceManager.GetString("DialogTitle_InvalidConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backupafspeellijst.
        /// </summary>
        public static string FallbackPlaylist {
            get {
                return ResourceManager.GetString("FallbackPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laden….
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laguna Preview 4 Player.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgende 20 nummers.
        /// </summary>
        public static string Next20Tracks {
            get {
                return ResourceManager.GetString("Next20Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zitten geen nummers in de afspeellijst.
        /// </summary>
        public static string NoTracksInPlaylist {
            get {
                return ResourceManager.GetString("NoTracksInPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er staan geen nummers in de wachtrij.
        /// </summary>
        public static string NoTracksInUserQueue {
            get {
                return ResourceManager.GetString("NoTracksInUserQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen nummers om af te spelen.
        /// </summary>
        public static string NoTracksToPlay {
            get {
                return ResourceManager.GetString("NoTracksToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (aan het downloaden).
        /// </summary>
        public static string PlayerTitle_Downloading {
            get {
                return ResourceManager.GetString("PlayerTitle_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vernieuwen.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backupafspeellijst vernieuwen.
        /// </summary>
        public static string RefreshFallbackPlaylist {
            get {
                return ResourceManager.GetString("RefreshFallbackPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dienst is momenteel niet beschikbaar.
        /// </summary>
        public static string ServiceCurrentlyNotAvailable {
            get {
                return ResourceManager.GetString("ServiceCurrentlyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgegaan.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie uitzetten.
        /// </summary>
        public static string TurnApplicationOff {
            get {
                return ResourceManager.GetString("TurnApplicationOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatie aanzetten.
        /// </summary>
        public static string TurnApplicationOn {
            get {
                return ResourceManager.GetString("TurnApplicationOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikerswachtrij.
        /// </summary>
        public static string UserQueue {
            get {
                return ResourceManager.GetString("UserQueue", resourceCulture);
            }
        }
    }
}
